### ISSUE TITLE
Feature Request: randomised player count for solo players

### ISSUE THREAD

**Issue by mccrispy** [SteveBallantine/spirit-island-randomiser#12]
It would be really great if there was a "randomise player count using set value as maximum" check box next to player count. (Not great wording, but hopefully it's sufficient explanation)

**Comment by SteveBallantine** [comment]
Ah yes, for playing multiple spirits presumably?
Thanks, I will add this to the list!

**Comment by mccrispy** [comment]
Yeah, that's correct. When I'm playing solo, I play with 1-3 Spirits. Casual is definitely "true solo", but multi-spirit is important for remembering how the spirits work in multiplayer games (all those "target another spirit" powers!), so when I'm feeling the need of a challenge I might choose multi-spirit.

**Comment by SteveBallantine** [comment]
This is now implemented
