### ISSUE TITLE
Maps and Boards section broken

### ISSUE THREAD

**Issue by mccrispy** [SteveBallantine/spirit-island-randomiser#15]
Both of these sections are "collapsed" (they only have a header). It looks like what was done to accommodate the Horizons maps hadn't quite worried as intended.

**Comment by mccrispy** [comment]
I've tried this on Android with both DuckDuckGo and Brave browsers

**Comment by mccrispy** [comment]
Aha! I see, yes. 

wrt the Maps section, it seems to me that Spirit Count should default to 1. That way the Maps section won't collapse and it'll reduce the incidence of the error "Number of spirits must be 1 - 6"

However, the "Boards" section collapses when no selection has been made in the Maps section, so resolving the player count default fixes Maps, which in turn addresses Boards. 

Note that it's particularly weird that leaving Spirit Count at 0 then selecting "Randomise" sets Count at 0-1, which will error. Similarly, setting Count to ≥1 before selecting Randomise will result in a Max value of 1, which for Min values >1, sets Max<Min. It would be better to default to Min+1.

**Comment by SteveBallantine** [comment]
I think you're right. My original thinking was that defaulting to 0 means that the user MUST input some value. But even if they generate a setup with 1 player by mistake, they can just go back and adjust it, so I don't think that's a big deal.
Defaulting to 1 seems like a much better choice.

**Comment by SteveBallantine** [comment]
Number of spirits now defaults to 1. Max spirits also default to 1 for some behind the scenes reasons. I might address that at a later date, but possibly not.
