### ISSUE TITLE
UX with "No Scenario"

### ISSUE THREAD

**Issue by mccrispy** [SteveBallantine/spirit-island-randomiser#17]
The user has to make a selection in the Scenario section, even if they don't want a scenario. I feel it makes more sense to default to "No Scenario", though I understand that users _requiring_ a scenario would have to _deselect_ that option.

**Comment by SteveBallantine** [comment]
Yes, I'm not sure about this one, but it seems anecdotally that 'no scenario' would be the most common option. In which case, selecting it by default would make sense.

**Comment by SteveBallantine** [comment]
'No scenario' now defaults to selected.
