### ISSUE TITLE
"random thematic boards" warning triggers when thematic boards are not selected

### ISSUE THREAD

**Issue by mccrispy** [SteveBallantine/spirit-island-randomiser#18]
If I leave "Random Thematic Boards" at "Block" and then in the Maps section I select only "Standard", the warning about Random Thematic Boards is displayed with the generated setup - even though there are no Thematic Boards in the setup.

This warning should _only_ be displayed if Thematic Boards are part of the selection options AND Thematic Boards are included in the generated setup.

**Comment by mccrispy** [comment]
Actually, I suppose the warning should only be displayed if Thematic Boards are part of the setup. A slight logical change, but it makes logical sense.

**Comment by SteveBallantine** [comment]
You're right. This is something I had noticed myself, just decided not to do anything about because it would be a pita... I really should get it fixed though.

**Comment by SteveBallantine** [comment]
This warning no longer appears if the randomly selected map is not thematic.
