### ISSUE TITLE
FEATURE REQUEST: Complexity-based weighting

### ISSUE THREAD

**Issue by mccrispy** [SteveBallantine/spirit-island-randomiser#19]
I don't know about you, but a 3-Spirit game with River, Lightning and Shadow is very different from a game with - say - BoDaN, Vengeance and Fractured Days! It's not a _difficulty_ thing per se, more a cognitive load thing. I'd love it if I could set (custom) cognitive load factors for difficulty, based on number of Spirits and Spirit complexity.

I'd like to scale difficulty based on Spirit Count, and I'd like to scale difficulty based on Spirit complexity. My personal factors would perhaps be +⅓ difficulty per Spirit beyond the first and +⅓/-⅓ difficulty above below Medium complexity for Spirits. So a 3 Spirit game with Very Complex Spirits would be 2⅔ difficulty even without an Adversary. I'd like that to be factored in when the setup is created.

**Comment by SteveBallantine** [comment]
Interesting thoughts! Thanks for this (and all the other issues you've raised).

I love the idea, though it might require quite a bit of explanation.
I'm thinking maybe a separate value range would be better than making it part of the difficulty calculation though. Will put some thought into it.

**Comment by SteveBallantine** [comment]
Ah, I see.
This would be an on/off option then. Called something like 'Include spirit complexity in difficulty'.
I think that behind the scenes, it might cause some skewing of probablities, but the effect may not be significant.

Certainly doable though. Will see what I can do.

**Comment by SteveBallantine** [comment]
This option is now added. 
Currently, the difficulty adjustment is hard coded as making it configurable would add quite a bit of complexity.

I also tweaked the formula slightly to add more difficulty for subsequent spirits as it felt a bit off to me. The second spirit will be +1/3, but the third will be +2/3, the forth +1, etc.

I'm still not sure the balance of the numbers is quite right, but give it a go and let me know what you think.

**Comment by SteveBallantine** [comment]
Leaving open for feedback on this.

**Comment by mccrispy** [comment]
Nice! I like this and it seems to work how I'd imagined. I ran a few generated test cases and it looked like stuff that fitted my expectations. Thanks for this

**Comment by SteveBallantine** [comment]
Glad to hear you like it :)
