### ISSUE TITLE
Bug - Adversary level randomization

### ISSUE THREAD

**Issue by Tonshyen** [SteveBallantine/spirit-island-randomiser#21]
Set difficulty 0 - 20
Select certain Adversary level, e.g. only tick England level 6
Still generates every England level instead of only level 6

**Comment by Tonshyen** [comment]
Would also be nice if when an adversary is unticked, you could tick for example level 6 and it automatically ticks the adversary itself too. Otherwise you have to tick the adversary and untick levels 0-5 since it wont generate with just the level 6 ticked.

**Comment by SteveBallantine** [comment]
Just confirming I've reproduced this issue. Will get it sorted as soon as I can.
I'll also take a look at auto-ticking the adversary is a single level is selected. Should be simple enough, but sometimes those kind of things can be surprisingly tricky!

**Comment by SteveBallantine** [comment]
Added an automatic test for this scenario and fixed it.
