### ISSUE TITLE
Support launching Spirit Island digital

### ISSUE THREAD

**Issue by MigrantP** [SteveBallantine/spirit-island-randomiser#25]
Hi, I'm John Arnold from Handelabra Games. Just today we released a feature to allow other apps/sites to launch Spirit Island digital via custom URL right into the New Game screen with a given setup in place. If you're interested in integrating that, you can find the details here: https://www.handelabra.com/spirit-island-launch-url-specification

**Comment by SteveBallantine** [comment]
That's awesome! Thanks for letting me know.
I'll certainly be taking a look at doing this once I get a free minute.

Great job on the game btw, it's a real nice conversion. 😁

**Comment by SteveBallantine** [comment]
This is now complete.
I don't actually own SI digital, so I've used the website approach, rather than trying to directly open from steam or the mobile app.
If anyone could confirm it works fully, that would be great!

**Comment by MigrantP** [comment]
Seems to work. Found that passing adversaryLevel=0 is not something the game is happy about, I'll note that in the documentation and fix it for the next update. For adversary level 0, just don't pass that parameter.

**Comment by SteveBallantine** [comment]
Sorted that now. Thanks for checking.
