### ISSUE TITLE
"No Adversary" throws error with launcher

### ISSUE THREAD

**Issue by mccrispy** [SteveBallantine/spirit-island-randomiser#27]
Thanks very much for being the first with a web app that supports the Handelabra launcher! 

I set up No Adversary game and got

"The items listed below are not currently supported by Handelabra:

Adversary - No Adversary"

I _know_ that that's wrong! 😉

**Comment by SteveBallantine** [comment]
Ah, good spot!
Will get this sorted asap.

**Comment by SteveBallantine** [comment]
Fixed.
