### ISSUE TITLE
HoSI Boards for digital version

### ISSUE THREAD

**Issue by mccrispy** [SteveBallantine/spirit-island-randomiser#29]
HoSI includes boards F, G and H and the digital version supports HoSI. This means that the Randomizer needs to do a couple of things:

1. Add board F as a HoSI board so it can be added in games using the launcher (tremendous thanks for implementing the launcher BTW)
2. Ensure all HoSI board selections honour the Imbalanced Arcade Boards setting

Number 2 arises because I recently built a "Steam" preset that includes all the bits for Steam compatibility and the selected game threw an "Imbalanced Board config" warning - despite my preset having "Imbalanced Arcade Boards = BLOCK". Here's a screenshot from the Warning popup in Steam
![image](https://github.com/SteveBallantine/spirit-island-randomiser/assets/45431447/bc5ee379-c593-4919-a145-dfefad6b0e25)

**Comment by SteveBallantine** [comment]
Good points!
2 was simple to sort. I just didn't realise G and F had imbalanced combinations!
1 was a little trickier because items could only belong to one expansion previously. I've fixed that though, so should also be working fine now.

**Comment by mccrispy** [comment]
Looks good Steve, thanks! I knew that the JE boards had "imbalanced" warnings, but I hadn't realised that two of the HoSI ones did too until I saw the popup! But then it wouldn't be in the rulebook, because HoSI is "my first SI" and the boards aren't separate like in the rest of the family. 

Just one _slight_ wrinkle: you've added **board E** as JE/HS, whereas it should have been **board F** that is JE/HS. Board E is unique to JE. (The digital version supports boards A-D plus F-H, I guess we get board E when digital starts supporting JE - guessing - some time late this year)

**Comment by mccrispy** [comment]
Looks good Steve, thanks! I knew that the JE boards had "imbalanced" warnings, but I hadn't realised that two of the HoSI ones did too. But then it wouldn't be in the rulebook, because HoSI is "my first SI" and the boards aren't separate like in the rest of the family. 

Just one _slight_ wrinkle: you've added **board E** as JE/HS, whereas it should have been **board F** that is JE/HS. Board E is unique to JE. (The digital version supports boards A-D plus F-H, I guess we get board E when digital starts supporting JE - guessing - some time late this year)

**Comment by SteveBallantine** [comment]
Oops! Sorted that now.
