### ISSUE TITLE
FEATURE REQUEST: support Jagged Earth for Spirit Island digital launcher

### ISSUE THREAD

**Issue by mccrispy** [SteveBallantine/spirit-island-randomiser#33]
I'm sure that this is on your "to do", but I thought that I'd give you a nudge anyway 😉

JE launches on Steam on Feb 29 and will support the following JE setup elements that are relevant to the launcher:

- Spirit: Vengeance as a Burning Plague
- Spirit: Stone's Unyielding Defiance
- Board: E + Southeast
- Board: (F) + Southwest (F is already supported via Horizons)
- Adversary: Habsburg Monarchy (Livestock Colony)

TBH, I don't know whether the launcher will support JE from day 1.

**Comment by SteveBallantine** [comment]
Thanks, I'll certainly aim to add support as soon as I can.
As you mention, I'm not sure if the launcher will support all this immediately or not, so will need to wait and see. :)

**Comment by mccrispy** [comment]
The list of canonical names has been updated to include the JE phase 1 content. I have been assured by MigrantP that the canonical list will always be current for all supported content. 

I guess this phased release means that you can't enable support at the expansion level, you'll have to enable it at the "released content" level. Should be doable (says I, a non-coder!)

**Comment by MigrantP** [comment]
There's no such thing as a launcher. There's just the game. You can pass whatever you want to it via the URL, and if it recognizes an identifier, it will use it; if it doesn't, it will ignore it.

**Comment by SteveBallantine** [comment]
Sorry it's taken so long. Been a busy year!
I've added all the currently supported items.
