### ISSUE TITLE
Feature Request: User-defined Presets

### ISSUE THREAD

**Issue by mccrispy** [SteveBallantine/spirit-island-randomiser#6]
Some days I'm feeling hardcore, others I feel more casual or have a desire to explore. It would be great to have the capability to save a set of options as a preset and be able to quickly switch between those presets

**Comment by SteveBallantine** [comment]
Thanks for the feedback. I like the idea.
Should be relatively simple to implement as well.

**Comment by SteveBallantine** [comment]
This was a little more complicated than I expected (aren't they always!) but presets are now available.
Hopefully it makes sense. The tooltips are behaving a little strangely on mobile, I'll try to get that sorted soon.
