### ISSUE TITLE
Thematic Boards - only NE gets chosen

### ISSUE THREAD

**Issue by mccrispy** [SteveBallantine/spirit-island-randomiser#8]
I understand what random means, but I have yet to see **any** thematic board other than NE in my generated setup. I generated 24+ results where a thematic board was part of the setup and it was NE _every_ time!

My board selection options are:
- Branch & Claw
- All Boards (i.e. A, B, C & D)
- Maps
  - Standard
  - Thematic (+ Tokens)

**Comment by Steve51D** [comment]
You'll also need to set the `Random Thematic Boards` option to `Allow` or `Force`. Otherwise, you'll always get the 'definitive' thematic boards for the given number of players. (Which is NE for 1 player).

Could you confirm if that's the case? Thanks.

**Comment by SteveBallantine** [comment]
Thanks, I'll have a think about how to present that more clearly.

**Comment by SteveBallantine** [comment]
Considering adding a warning on the result screen in the 'spirits and starting boards' section.
This would only be displayed if thematic boards were selected and `random thematic boards` was set to `block`.
It would say something like 
 > Warning: `random thematic boards` set to `block`. This means that the same 'definitive' thematic boards will always be selected based on the number of boards needed, as described in the Spirit Island rulebook.

This warning could be permanently dismissed, so if you didn't want it bugging you, it would only be displayed once.
How does that sound?

**Comment by mccrispy** [comment]
Sounds great! Perhaps a reference to the section of the rulebook that the info can be found in would be extra helpful. (I guess it's in "Thematic Boards", right? 😀)

**Comment by SteveBallantine** [comment]
Done
