### ISSUE TITLE
Aspects as part of Options block

### ISSUE THREAD

**Issue by mccrispy** [SteveBallantine/spirit-island-randomiser#9]
I really like the possibility of including Aspects in my generator set, but it makes configuring my generator set much more fiddly. Would it be possible to have an Option to Block/Allow/Force Aspects so I could ignore (or not be presented with) the check boxes for Aspects.

Or maybe move Aspects out of the Spirits selection and into their own block so they can more easily be enabled/disabled "en mass"

**Comment by SteveBallantine** [comment]
I hear what you're saying with the fiddlyness. However, I definitely don't like the idea of moving the aspects into thier own group. They really belong with the spirits imo.
I think that an allow/block/force option seems like a nice way to control it (defaulting to allow). I'll add that in when I get a minute.

**Comment by SteveBallantine** [comment]
This is option is now available! Let me kow what you think.

**Comment by mccrispy** [comment]
This works for my use case - at least in part. I have realised that if "profiles" get implemented, I could always save a profile that disabled the Aspects that I didn't want to use. SI the two features between them will address my use case.
